### ISSUE TITLE
JSON Parse Error when creating a plugin with this Template

### ISSUE THREAD

**Issue by BJClark** [skpm/with-datasupplier#1]
I am trying to create a new data supplier plugin, and running this command throws an JSON parse error:

`➜ skpm create test
✔ Done!

The Sketch developer mode is not enabled (http://developer.sketchapp.com/introduction/preferences/#always-reload-scripts-before-running).
Do you want to enable it? (y/N)

To get started, cd into the new directory:
  cd test

To start a development live-reload build:
  npm run start

To build the plugin:
  npm run build

To publish the plugin:
  skpm publish

~/Development took 26s
➜ skpm create testdatasupplier --template=skpm/with-datasupplier
⠇ Fetching the template
✖ ERROR SyntaxError: Unexpected token } in JSON at position 588
SyntaxError: Unexpected token } in JSON at position 588
    at JSON.parse (<anonymous>)
    at /Users/willclark/.nvm/versions/node/v13.0.1/lib/node_modules/skpm/lib/commands/create.js:249:24
    at Generator.next (<anonymous>)
    at step (/Users/willclark/.nvm/versions/node/v13.0.1/lib/node_modules/skpm/lib/commands/create.js:53:191)
    at /Users/willclark/.nvm/versions/node/v13.0.1/lib/node_modules/skpm/lib/commands/create.js:53:361
`

As you can see, the error doesn't happen with a standard sketch plugin template. -h doesn't seem to mention a debug or verbose mode, so I'm not sure how to isolate which file npm is choking on.

**Comment by BJClark** [comment]
I figured out you get a debug log via `npm run build` and I fixed the offending comma. PR here: https://github.com/skpm/with-datasupplier/pull/2
